# Generated by Django 5.0.6 on 2024-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_bannerimage_title_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
